version: "3.7"

services:
  mysqldb:
    image: "mysql:5.7"
    container_name: dbmysql_new
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Allow empty password (for dev purposes)
      - MYSQL_DATABASE=kaddem  # Default database name
      - MYSQL_ROOT_PASSWORD=root_password  # Set root password for MySQL
    ports:
      - "3306:3306"  # Map MySQL port
    volumes:
      - db:/var/lib/mysql  # Persist MySQL data

  app-timesheet:
    depends_on:
      - mysqldb  # Wait for MySQL to start before the app
    build:
      context: .  # Use the Dockerfile in the current directory
      dockerfile: Dockerfile  # Specify Dockerfile if named differently
    restart: on-failure  # Restart policy
    ports:
      - "8089:8089"  # Map application port
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY

volumes:
  db:  # Declare a volume for MySQL data
