# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/prometheus' 
    static_configs:
      - targets: ['localhost:8080']
  
  - job_name: 'grafana'
    metrics_path: '/metrics'  # Grafana's metrics endpoint
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kaddem'
    metrics_path: '/Kaddem/actuator/prometheus'
    static_configs:
      - targets: ['kaddem-app:8089']
